name: Default Workflow

on:
  push:
    branches: [ "master" ]

jobs:
  flutter_job:

    # The machine, we can also use windows-latest or ubuntu-latest
    # We are choosing macos-latest because we will be also building for iOS
    runs-on: macos-latest

    steps:

      # Clones the project on the machine
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Fetches proj dependencies from pub
      - name: Install dependencies
        run: flutter pub get

      - name: Build flutter web
        run: flutter build web --release

      - name: Set up node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project currencycv-15ac0
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      